<div class="smartcaption taglefttitleleft animated">
<% if(paramcaptioncaptiontag != ''){ %>
  <div class="caption-h4">{param text "Caption tag"}</div>
<% } %>
<% if(paramcaptioncaptiontitle != ''){ %>
<div class="caption-h3">{param text "Caption title" "Required field"}</div>
<% } %>
</div>
<script type="text/javascript">
var caption = {
  w: "{param text "Width of the title in px" "200px"}",
  type: "taglefttitleleft",
  mode: "div",
  top: "{param text "Top coordinate of the tag" "0px" "This helps to position the caption on your slide."}",
  horizontaloffset: "{param text "Horizontal offset" "0px" "This helps to position the caption on your slide."}",
  interval: {param text "Animation interval" "1000"},
  delay: {param text "Animation delay" "0" "in ms"},
  easing: "{param easing "Animation easing"}"
};
</script>