<object id="youtube{param text "Video code" "" "Insert here only the bold text from the url example: http://www.youtube.com/watch?v"}" width="{param text "Video width" "100%" "Just a number! Usually the canvas width."}" height="{param text "Video height" "100%" "Just a number! Usually the canvas height."}">
  <param name="movie" value="http://www.youtube.com/v/{param text "Video code"}?version=3&amp;enablejsapi=1&amp;playerapiid=youtube{param text "Video code"}&amp;hd=1&amp;autohide=1&amp;controls=1&amp;showinfo=0&amp;iv_load_policy=3&amp;theme=dark&amp;rel=0" />
  <param name="allowFullScreen" value="true" />
  <param name="allowscriptaccess" value="always" />
  <param name="wmode" value="opaque" />
  <embed src="http://www.youtube.com/v/{param text "Video code"}?version=3&amp;enablejsapi=1&amp;playerapiid=youtube{param text "Video code"}&amp;hd=1&amp;autohide=1&amp;controls=1&amp;showinfo=0&amp;iv_load_policy=3&amp;theme=dark&amp;ap=%2526fmt%3D18&amp;rel=0" wmode="opaque" type="application/x-shockwave-flash" width="{param text "Video width"}" height="{param text "Video height"}" allowscriptaccess="always" allowfullscreen="true">
  </embed>
</object>
<script type="text/javascript">
if(!odojo.hasFlash){
  var tag = document.createElement("script");
  tag.src = "//www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName("script")[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  var node = odojo.byId("youtube{param text "Video code"}");
  node.parentNode.innerHTML = "<iframe class=\"youtubeapi\" id=\"youtube{param text \"Video code\"}\" width=\"{param text \"Video width\"}\" height=\"{param text \"Video height\"}\" src=\"http://www.youtube.com/embed/{param text \"Video code\"}?hd=1&enablejsapi=1&playerapiid=youtube{param text \"Video code\"}&autohide=1&controls=1&showinfo=0&iv_load_policy=3&theme=dark&html5=1&ap=%2526fmt%3D18&rel=0&wmode=transparent\" frameborder=\"0\" allowfullscreen></iframe>";
  function onYouTubeIframeAPIReady() {
    var players = odojo.query(".youtubeapi");
    for(var i = 0; i < players.length; i++){
      var player = new YT.Player(odojo.attr(players[i], "id"));
      players[i].parentNode.youtube = player;
    }
  }
}

function onYouTubePlayerReady(playerId) {
  var node = odojo.byId(playerId);
  var player = null;
  if(!node.getPlayerState){
    player = odojo.query("embed", node)[0];
  }else{
    player = node;
  }
  if(player && player.getPlayerState){
    node.parentNode.youtube = player;
  }
}
</script>